import { ARENA_HEIGHT, ARENA_WIDTH, waveLen, xpThreshold } from './constants';
import type { GameState, PlayerState, SystemsState } from './types';

export const BASE_PLAYER: PlayerState = {
  x: ARENA_WIDTH / 2,
  y: ARENA_HEIGHT / 2,
  weaponKey: null,
  hp: 10,
  maxHp: 10,
  shield: 0,
  moveSpeed: 210,
  cooldown: 0.72,
  damage: 2,
  projectiles: 1,
  range: 320,
  pierce: 0,
  magnet: 52,
  hitFlash: 0,
  isMoving: false,
  overdraw: false,
  overdrawHpCost: 0,
  leechOnHit: 0,
  overhealShield: false,
  missingHpDamageScale: 0,
  momentumEnabled: false,
  momentumMeter: 0,
  momentumAttackRate: 0,
  momentumDamage: 0,
  trailEnabled: false,
  trailDamagePerSecond: 0,
  pickupHasteTime: 0,
  pickupHasteStrength: 0,
  harvestLineEnabled: false,
  momentumMagnetBonus: 0,
  movingPierceBonus: 0,
  weaponSpread: 0.22,
  movingDamageBonus: 0,
  shotSpeed: 520,
  shotSize: 4,
  shotColor: '#f8fafc',
  shotStyle: 'bolt',
  boomRate: 1,
  boomDot: 0,
  boomDotTime: 0,
};

export const BASE_SYSTEMS: SystemsState = {
  baseBloodNuggetDropChance: 0.16,
  bloodNuggetDropChance: 0.16,
  bloodNuggetHeal: 1,
  corpseExplosionRadius: 0,
  corpseExplosionDamage: 0,
  ashWakeEnabled: false,
  ashWakeDps: 0,
  ashWakeDuration: 0,
  funeralHeatEnabled: false,
  funeralHeatAttackRate: 0,
  funeralHeatTime: 0,
  chainXpBonus: 0,
};

export const initGame = (): GameState => ({
  phase: 'start',
  time: 0,
  wave: 1,
  waveTime: waveLen(1),
  level: 1,
  xp: 0,
  xpTarget: xpThreshold(1),
  pendingLevelUps: 0,
  kills: 0,
  player: { ...BASE_PLAYER },
  systems: { ...BASE_SYSTEMS },
  enemies: [],
  projectiles: [],
  drops: [],
  trail: [],
  ash: [],
  expl: [],
  floaters: [],
  spawns: [],
  messages: ['Choose a starting weapon.'],
  offered: [],
  got: [],
  acquiredUpgrades: [],
  permKeys: [],
  wavePicks: [],
  synthKeep: [],
  synthBurn: [],
  juice: 2,
  spawnBudget: 0,
  spawnCooldown: 1.4,
  invuln: 0,
});
