import React,{useEffect,useMemo,useRef,useState}from"react";

const W=960,H=600,PR=14,DR=6,WAVE_BASE=35;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),rand=(a,b)=>Math.random()*(b-a)+a;
const gid=(()=>{let n=0;return()=>`${Date.now()}-${n++}`})();
const pick=(arr,n)=>{const a=[...arr],out=[];while(a.length&&out.length<n)out.push(a.splice(Math.floor(Math.random()*a.length),1)[0]);return out};
const fmt=t=>`${String(Math.floor(Math.max(0,t)/60)).padStart(2,"0")}:${String(Math.ceil(Math.max(0,t)%60)).padStart(2,"0")}`;
const waveLen=w=>Math.max(24,WAVE_BASE+Math.min(18,w*3));

const P0={x:W/2,y:H/2,weaponKey:null,hp:10,maxHp:10,shield:0,moveSpeed:210,cooldown:.72,damage:2,projectiles:1,range:320,pierce:0,magnet:52,hitFlash:0,isMoving:false,overdraw:false,overdrawHpCost:0,leechOnHit:0,overhealShield:false,missingHpDamageScale:0,momentumEnabled:false,momentumMeter:0,momentumAttackRate:0,momentumDamage:0,trailEnabled:false,trailDamagePerSecond:0,pickupHasteTime:0,pickupHasteStrength:0,harvestLineEnabled:false,momentumMagnetBonus:0,movingPierceBonus:0,weaponSpread:.22,movingDamageBonus:0,shotSpeed:520,shotSize:4,shotColor:"#f8fafc",shotStyle:"bolt",boomRate:1,boomDot:0,boomDotTime:0};
const S0={baseBloodNuggetDropChance:.16,bloodNuggetDropChance:.16,bloodNuggetHeal:1,corpseExplosionRadius:0,corpseExplosionDamage:0,ashWakeEnabled:false,ashWakeDps:0,ashWakeDuration:0,funeralHeatEnabled:false,funeralHeatAttackRate:0,funeralHeatTime:0,chainXpBonus:0};
const WPN=(k,title,role,stats,effect,player,systems,message)=>({k,title,role,stats,effect,player,systems,message,apply:(p,s)=>({player:{...p,weaponKey:k,...player},systems:{...s,...systems},message})});
const WEAPONS=[
WPN("graveWand","Grave Wand","Balanced",[{label:"Damage",value:"2.2"},{label:"Range",value:"340"},{label:"Speed",value:"0.72"}],"Steady all-around starter.",{damage:2.2,cooldown:.72,projectiles:1,range:340,pierce:0,shotSpeed:160,shotSize:4,shotColor:"#e2e8f0",shotStyle:"bolt",weaponSpread:0,movingDamageBonus:0},{bloodNuggetDropChance:S0.baseBloodNuggetDropChance,corpseExplosionRadius:0,corpseExplosionDamage:0},"Grave Wand equipped."),
WPN("bloodNeedle","Blood Needle","Risk / DPS",[{label:"Damage",value:"1.2"},{label:"Range",value:"220"},{label:"Speed",value:"0.38"}],"Rapid shots. Costs HP to fire and drops more Blood Nuggets.",{damage:1.2,cooldown:.38,projectiles:1,range:220,pierce:0,overdraw:true,overdrawHpCost:.1,shotSpeed:310,shotSize:3,shotColor:"#fb7185",shotStyle:"needle",weaponSpread:0,movingDamageBonus:0},{bloodNuggetDropChance:S0.baseBloodNuggetDropChance+.1,corpseExplosionRadius:0,corpseExplosionDamage:0},"Blood Needle equipped."),
WPN("sickleArc","Sickle Arc","Mobile",[{label:"Damage",value:"2.8/s"},{label:"Range",value:"175"},{label:"Speed",value:"0.90"}],"A spinning sickle hunts a target, then inflicts damage over time.",{damage:0,cooldown:.9,projectiles:1,range:175,pierce:1,shotSpeed:210,shotSize:7,shotColor:"#86efac",shotStyle:"boomerang",boomRate:.5,boomDot:2.8,boomDotTime:1.2,weaponSpread:0,movingDamageBonus:.2},{bloodNuggetDropChance:S0.baseBloodNuggetDropChance,corpseExplosionRadius:0,corpseExplosionDamage:0},"Sickle Arc equipped."),
WPN("bloomStaff","Bloom Staff","AoE",[{label:"Damage",value:"1.3"},{label:"Range",value:"380"},{label:"Speed",value:"0.82"}],"Kills explode and damage nearby enemies.",{damage:1.3,cooldown:.82,projectiles:1,range:380,pierce:0,shotSpeed:170,shotSize:7,shotColor:"#fbbf24",shotStyle:"bloom",weaponSpread:0,movingDamageBonus:0},{bloodNuggetDropChance:S0.baseBloodNuggetDropChance,corpseExplosionRadius:42,corpseExplosionDamage:4},"Bloom Staff equipped.")];
const wBy=k=>WEAPONS.find(w=>w.k===k)||WEAPONS[0];
const xpT=l=>Math.max(2,Math.floor((10+l*7+l*l*1.35)*.25));
const got=s=>s.got||s.acquiredUpgrades||[];
const uniq=(s,k)=>!got(s).includes(k);
const meter=p=>p.momentumEnabled?p.momentumMeter||0:0;
const mBonus=p=>p.missingHpDamageScale?((p.maxHp-p.hp)/Math.max(1,p.maxHp))*p.missingHpDamageScale:0;
const mag=p=>(p.magnet||0)+(p.momentumMagnetBonus||0)*meter(p);
const dropChance=(s,e)=>clamp((s.bloodNuggetDropChance??S0.bloodNuggetDropChance)+(e?.elite?.18:0),0,.9);
const ash=(x,y,s)=>({id:gid(),x,y,radius:(s.corpseExplosionRadius||36)*.7,life:s.ashWakeDuration||.7});
const hash=s=>[...s].reduce((a,c)=>a+c.charCodeAt(0),0);
const juiceMeta=u=>{const base={Stats:[2,1],Blood:[3,2],Momentum:[3,2],Bloom:[4,2],General:[3,1]}[u.family]||[3,1],h=hash(u.key);return{cost:base[0]+h%3,gain:base[1]+h%2}};

const init=()=>({phase:"start",time:0,wave:1,waveTime:waveLen(1),level:1,xp:0,xpTarget:xpT(1),pendingLevelUps:0,kills:0,player:{...P0},systems:{...S0},enemies:[],projectiles:[],drops:[],trail:[],ash:[],expl:[],floaters:[],spawns:[],messages:["Choose a starting weapon."],offered:[],got:[],acquiredUpgrades:[],permKeys:[],wavePicks:[],synthKeep:[],synthBurn:[],juice:2,spawnBudget:0,spawnCooldown:1.4,invuln:0});
const addGot=(s,k)=>({...s,got:[...got(s),k],acquiredUpgrades:[...got(s),k]});
const UP=(key,title,body,apply,canTake=s=>uniq(s,key),family="General")=>({key,title,body,apply,canTake,family});
const U=[
UP("damage","Heavy Bolts","+1 projectile damage.",s=>{s=addGot(s,"damage");return{...s,player:{...s.player,damage:s.player.damage+1}}},s=>uniq(s,"damage"),"Stats"),
UP("splitVolley","Split Volley","+1 projectile per attack.",s=>{s=addGot(s,"splitVolley");return{...s,player:{...s.player,projectiles:s.player.projectiles+1}}},s=>uniq(s,"splitVolley"),"Stats"),
UP("graveDrill","Grave Drill","+1 pierce.",s=>{s=addGot(s,"graveDrill");return{...s,player:{...s.player,pierce:s.player.pierce+1}}},s=>uniq(s,"graveDrill"),"Stats"),
UP("rangeUp","Longshot","+80 projectile range.",s=>{s=addGot(s,"rangeUp");return{...s,player:{...s.player,range:s.player.range+80}}},s=>uniq(s,"rangeUp"),"Stats"),
UP("moonstep","Moonstep","+14% move speed.",s=>{s=addGot(s,"moonstep");return{...s,player:{...s.player,moveSpeed:s.player.moveSpeed*1.14}}},s=>uniq(s,"moonstep"),"Stats"),
UP("ironVeins","Iron Veins","+2 max HP • Heal 2 • Blood Nuggets heal +1.",s=>{s=addGot(s,"ironVeins");return{...s,player:{...s.player,maxHp:s.player.maxHp+2,hp:clamp(s.player.hp+2,0,s.player.maxHp+2)},systems:{...s.systems,bloodNuggetHeal:s.systems.bloodNuggetHeal+1}}},s=>uniq(s,"ironVeins"),"Stats"),
UP("overdraw","Overdraw","Shots cost 0.45 HP • -30% cooldown • +1 damage • +5% Blood Nugget chance.",s=>{s=addGot(s,"overdraw");return{...s,player:{...s.player,overdraw:true,overdrawHpCost:.45,cooldown:Math.max(.14,s.player.cooldown*.7),damage:s.player.damage+1},systems:{...s.systems,bloodNuggetDropChance:Math.min(.4,s.systems.bloodNuggetDropChance+.05)}}},s=>uniq(s,"overdraw"),"Blood"),
UP("leechBolts","Leech Bolts","+0.12 HP per projectile hit.",s=>{s=addGot(s,"leechBolts");return{...s,player:{...s.player,leechOnHit:s.player.leechOnHit+.12}}},s=>uniq(s,"leechBolts"),"Blood"),
UP("freshVeins","Fresh Veins","Blood Nuggets heal +1 • +8% drop chance • +18 pickup range.",s=>{s=addGot(s,"freshVeins");return{...s,systems:{...s.systems,bloodNuggetHeal:s.systems.bloodNuggetHeal+1,bloodNuggetDropChance:Math.min(.55,s.systems.bloodNuggetDropChance+.08)},player:{...s.player,magnet:s.player.magnet+18}}},s=>uniq(s,"freshVeins"),"Blood"),
UP("redSurge","Red Surge","Excess healing converts to decaying shield.",s=>{s=addGot(s,"redSurge");return{...s,player:{...s.player,overhealShield:true}}},s=>uniq(s,"redSurge"),"Blood"),
UP("hemorrhageEngine","Hemorrhage Engine","+1.2x damage scaling based on missing HP.",s=>{s=addGot(s,"hemorrhageEngine");return{...s,player:{...s.player,missingHpDamageScale:s.player.missingHpDamageScale+1.2}}},s=>uniq(s,"hemorrhageEngine"),"Blood"),
UP("momentum","Momentum","Movement builds momentum • Up to +45% attack rate • Up to +25% damage.",s=>{s=addGot(s,"momentum");return{...s,player:{...s.player,momentumEnabled:true,momentumAttackRate:s.player.momentumAttackRate+.45,momentumDamage:s.player.momentumDamage+.25}}},s=>uniq(s,"momentum"),"Momentum"),
UP("trailBite","Trail Bite","Leaves trail dealing 4 DPS while moving.",s=>{s=addGot(s,"trailBite");return{...s,player:{...s.player,trailEnabled:true,trailDamagePerSecond:s.player.trailDamagePerSecond+4}}},s=>uniq(s,"trailBite"),"Momentum"),
UP("harvestLine","Harvest Line","XP pickup grants haste for a short duration.",s=>{s=addGot(s,"harvestLine");return{...s,player:{...s.player,harvestLineEnabled:true,pickupHasteStrength:s.player.pickupHasteStrength+.22}}},s=>uniq(s,"harvestLine"),"Momentum"),
UP("runnersHunger","Runner's Hunger","+36 pickup range at max momentum.",s=>{s=addGot(s,"runnersHunger");return{...s,player:{...s.player,momentumMagnetBonus:s.player.momentumMagnetBonus+36}}},s=>uniq(s,"runnersHunger"),"Momentum"),
UP("driftVolley","Drift Volley","+1 pierce while moving.",s=>{s=addGot(s,"driftVolley");return{...s,player:{...s.player,movingPierceBonus:s.player.movingPierceBonus+1}}},s=>uniq(s,"driftVolley"),"Momentum"),
UP("corpseBloom","Corpse Bloom","On death: explode (radius +34 • damage +6).",s=>{s=addGot(s,"corpseBloom");return{...s,systems:{...s.systems,corpseExplosionRadius:s.systems.corpseExplosionRadius+34,corpseExplosionDamage:s.systems.corpseExplosionDamage+6}}},s=>uniq(s,"corpseBloom"),"Bloom"),
UP("ashWake","Ash Wake","Explosions create zones dealing +8 DPS.",s=>{s=addGot(s,"ashWake");return{...s,systems:{...s.systems,ashWakeEnabled:true,ashWakeDps:s.systems.ashWakeDps+8,ashWakeDuration:s.systems.ashWakeDuration+.7}}},s=>uniq(s,"ashWake")&&s.systems.corpseExplosionRadius>0,"Bloom"),
UP("funeralHeat","Funeral Heat","Explosion kills grant +45% attack rate briefly.",s=>{s=addGot(s,"funeralHeat");return{...s,systems:{...s.systems,funeralHeatEnabled:true,funeralHeatAttackRate:s.systems.funeralHeatAttackRate+.45}}},s=>uniq(s,"funeralHeat")&&s.systems.corpseExplosionRadius>0,"Bloom"),
UP("chainLedger","Chain Ledger","+1 XP per explosion kill.",s=>{s=addGot(s,"chainLedger");return{...s,systems:{...s.systems,chainXpBonus:s.systems.chainXpBonus+1}}},s=>uniq(s,"chainLedger")&&s.systems.corpseExplosionRadius>0,"Bloom"),
UP("bloomRadius","Bloom Radius","+24 explosion radius • +5 explosion damage.",s=>{s=addGot(s,"bloomRadius");return{...s,systems:{...s.systems,corpseExplosionRadius:s.systems.corpseExplosionRadius+24,corpseExplosionDamage:s.systems.corpseExplosionDamage+5}}},s=>uniq(s,"bloomRadius")&&s.systems.corpseExplosionRadius>0,"Bloom")
];
const uBy=k=>U.find(u=>u.key===k);
const sample=s=>{const a=U.filter(u=>u.canTake(s)),b=a.filter(u=>u.family==="Stats"),n=a.filter(u=>u.family!=="Stats"),x=pick(b,Math.min(1,b.length)),y=pick(n.length?n:b,3-x.length);return[...x,...y].filter((u,i,arr)=>arr.findIndex(v=>v.key===u.key)===i).slice(0,3)};
const enter=s=>s.pendingLevelUps<=0?s:{...s,phase:"levelup",pendingLevelUps:s.pendingLevelUps-1,offered:sample(s),messages:[`Level ${s.level}. Choose an upgrade.`]};
function rebuildPermanent(prev,keys){const weapon=wBy(prev.player.weaponKey).apply({...P0}, {...S0});let s={...prev,player:{...weapon.player,x:W/2,y:H/2,hp:Math.min(prev.player.hp,weapon.player.maxHp),shield:0,hitFlash:0,momentumMeter:0},systems:{...weapon.systems},got:[],acquiredUpgrades:[]};for(const k of keys){const u=uBy(k);if(u)s=u.apply(s)}return{...s,permKeys:[...keys]}}

const mkEnemy=(x,y,t=0,kind="chaser",slot=0)=>{const elite=Math.random()<Math.min(.08,.015+t/500),base={id:gid(),x,y,r:elite?15:11,hp:elite?10+t*.08:4+t*.035,maxHp:elite?10+t*.08:4+t*.035,speed:elite?48:65,damage:elite?2:1,color:elite?"#f97316":"#c084fc",elite,moveType:kind,flankDir:Math.random()<.5?-1:1,packSlot:slot,laneBias:rand(.75,1.25),trapRange:elite?44:34,phase:rand(0,Math.PI*2),dotTime:0,dotDps:0};
if(kind==="chaser")return{...base,color:elite?"#fb923c":"#f472b6",speed:elite?60:82,burstCd:rand(1.2,2.2),burstTime:0};
if(kind==="orbit")return{...base,color:elite?"#a78bfa":"#818cf8",speed:elite?54:72,orbitDir:Math.random()<.5?-1:1,feintCd:rand(1.2,2.2),feintTime:0};
if(kind==="zigzag")return{...base,color:elite?"#38bdf8":"#22d3ee",speed:elite?72:92,drift:rand(.75,1.35),weaveFlip:Math.random()<.5?-1:1};
if(kind==="scout")return{...base,color:elite?"#facc15":"#bef264",r:elite?12:9,hp:elite?7+t*.05:3+t*.025,maxHp:elite?7+t*.05:3+t*.025,speed:elite?92:118,dashCd:rand(.45,1),dashTime:0,dashAngle:0};
return{...base,color:elite?"#f87171":"#94a3b8",r:elite?19:16,hp:elite?18+t*.12:9+t*.065,maxHp:elite?18+t*.12:9+t*.065,speed:elite?35:42,damage:elite?3:2,slamCd:rand(1.8,3),slamTime:0,windup:0,chargeTime:0,chargeAngle:0};};
function spawnType(t=0){const types=t<20?["chaser","orbit","zigzag"]:t<70?["chaser","orbit","zigzag","scout"]:["chaser","orbit","zigzag","scout","tank"];return types[Math.floor(Math.random()*types.length)]}
function spawnAnchor(){const side=Math.floor(Math.random()*4),m=34,pad=70;if(side===0)return{x:rand(pad,W-pad),y:m,side};if(side===1)return{x:W-m,y:rand(pad,H-pad),side};if(side===2)return{x:rand(pad,W-pad),y:H-m,side};return{x:m,y:rand(pad,H-pad),side}}
function groupOffset(i,total,side){const slot=i-(total-1)/2,spread=24,jitter=8,along=slot*spread+rand(-jitter,jitter),deep=rand(-6,18),horizontal=side===0||side===2;return{x:horizontal?along:(side===1?-deep:deep),y:horizontal?(side===0?deep:-deep):along,slot}}
function spawnEnemy(t=0,slot=0,total=1,anchor=spawnAnchor()){const o=groupOffset(slot,total,anchor.side);return mkEnemy(clamp(anchor.x+o.x,20,W-20),clamp(anchor.y+o.y,20,H-20),t,spawnType(t),o.slot)}
function spawnGroup(t=0){const count=t<35?2:t<100?3:Math.min(5,3+Math.floor((t-100)/90)),anchor=spawnAnchor();return Array.from({length:count},(_,i)=>spawnEnemy(t,i,count,anchor))}
const mkShot=(p,t,ang,sp,m,movePierce,i)=>({id:gid(),x:p.x,y:p.y,px:p.x,py:p.y,ox:p.x,oy:p.y,tid:t.id,tx:t.x,ty:t.y,bx:p.x,by:p.y,didBounce:false,vx:Math.cos(ang)*sp,vy:Math.sin(ang)*sp,life:(p.range||320)/sp,maxLife:(p.range||320)/sp,damage:Math.max(0,p.damage*m),dotDps:(p.boomDot||0)*m,dotTime:p.boomDotTime||0,pierceLeft:p.pierce+movePierce,size:p.shotSize||4,color:p.shotColor||"#f8fafc",style:p.shotStyle||"bolt",hitIds:[],curve:i%2===0?1:-1,baseAngle:ang,spin:0});
function fireShots(p,enemies){const range=p.range||320;if(!enemies.length)return[];const inRange=enemies.filter(e=>dist(p,e)<=range);if(!inRange.length)return[];const t=[...inRange].sort((a,b)=>dist(p,a)-dist(p,b))[0],a=Math.atan2(t.y-p.y,t.x-p.x),spread=p.projectiles===1?0:p.weaponSpread||.22,m=1+mBonus(p)+meter(p)*(p.momentumDamage||0)+(p.pickupHasteTime||0)*(p.pickupHasteStrength||0)*.35+(p.isMoving?(p.movingDamageBonus||0):0),movePierce=p.isMoving?p.movingPierceBonus:0,sp=p.shotSpeed||520;return Array.from({length:p.projectiles},(_,i)=>mkShot(p,t,a+(i-(p.projectiles-1)/2)*spread,sp,m,movePierce,i))}
const shots=fireShots;
function selfCheck(){const g=init(),e=enter({...g,pendingLevelUps:1,level:2}),p={...g.player,range:100,projectiles:1,weaponSpread:0},far={id:"f",x:p.x+300,y:p.y,r:12,hp:4,maxHp:4,speed:0,damage:1,color:"#fff",elite:false},near={...far,id:"n",x:p.x+50},bn=wBy("bloodNeedle").apply(g.player,g.systems).player,sa=wBy("sickleArc").apply(g.player,g.systems).player,bs=wBy("bloomStaff").apply(g.player,g.systems).player;if(!Array.isArray(g.got)||!Array.isArray(g.acquiredUpgrades)||!uniq(g,"damage"))throw Error("upgrade_state");if(addGot(g,"damage").got.length!==1||uniq(addGot(g,"damage"),"damage"))throw Error("upgrade_tracking");if(juiceMeta(U[0]).cost<2||juiceMeta(U[0]).gain<1)throw Error("juice_meta");if(waveLen(1)<20||waveLen(3)<waveLen(1))throw Error("wave_timer");if(xpT(1)<2||xpT(2)<xpT(1))throw Error("xp");if(e.phase!=="levelup"||e.pendingLevelUps!==0||!e.offered.length)throw Error("level");if(shots(p,[far]).length!==0||shots(p,[near]).length!==1||shots({...p,projectiles:3},[near]).length!==3||!Array.isArray(shots({...p,pierce:1},[near])[0]?.hitIds))throw Error("shots");if(wBy("graveWand").k!=="graveWand")throw Error("weapon");if(Math.abs(dropChance(S0,{elite:true})-.34)>.0001||Math.abs(dropChance(S0,{elite:false})-.16)>.0001)throw Error("drop");const se=spawnEnemy(0),sg=spawnGroup(0),spread=Math.max(...sg.map(a=>Math.max(...sg.map(b=>dist(a,b)))));if(!["chaser","orbit","zigzag","scout","tank"].includes(se.moveType)||sg.length!==2||spread>90||typeof se.flankDir!=="number"||typeof se.packSlot!=="number")throw Error("enemy_move");if(!(bn.shotSpeed>sa.shotSpeed&&bs.shotSize>bn.shotSize&&sa.projectiles===1&&sa.pierce>=1&&sa.shotStyle==="boomerang"&&sa.boomDot>0&&sa.damage===0&&shots(sa,[near])[0]?.tid===near.id&&bn.overdraw&&bs.range>sa.range&&bs.damage>=1.3&&wBy("bloomStaff").systems.corpseExplosionRadius>=42&&wBy("bloomStaff").systems.corpseExplosionDamage>=4))throw Error("weapon_identity");}

function stepBoom(v,n,dt){const rate=n.player.boomRate||1,target=n.enemies.find(e=>e.id===v.tid);if(target){v.tx=target.x;v.ty=target.y}v.life-=dt*rate;v.spin=(v.spin||0)+dt*18;const t=1-v.life/v.maxLife,split=.32;let tx=v.x,ty=v.y;if(t<split){const u=t/split,cx=v.ox+(v.tx-v.ox)*u,cy=v.oy+(v.ty-v.oy)*u,wob=Math.sin(u*Math.PI)*26;tx=cx+Math.cos(v.baseAngle+u*Math.PI*.9*v.curve)*wob;ty=cy+Math.sin(v.baseAngle+u*Math.PI*.9*v.curve)*wob}else{if(!v.didBounce){v.didBounce=true;v.bx=v.x;v.by=v.y}const u=(t-split)/(1-split),overshoot=.26+Math.min(.28,dist({x:v.bx,y:v.by},{x:v.tx,y:v.ty})/320),aimX=v.tx+(v.tx-v.bx)*overshoot,aimY=v.ty+(v.ty-v.by)*overshoot,lineEase=u*u*(3-2*u),lineX=v.bx+(aimX-v.bx)*lineEase,lineY=v.by+(aimY-v.by)*lineEase,toTarget=Math.atan2(aimY-v.by,aimX-v.bx),settle=Math.max(0,(u-.84)/.16),endX=aimX+(v.tx-aimX)*settle,endY=aimY+(v.ty-aimY)*settle,offset=Math.sin(u*Math.PI)*(4.5*(1-u));tx=lineX+(endX-lineX)*settle+Math.cos(toTarget+Math.PI*.5*v.curve)*offset;ty=lineY+(endY-lineY)*settle+Math.sin(toTarget+Math.PI*.5*v.curve)*offset}const f=Math.min(1,dt*15);v.x+=(tx-v.x)*f;v.y+=(ty-v.y)*f;}
function enemyGoal(v,n,k){const mvx=(k.d||k.arrowright?1:0)-(k.a||k.arrowleft?1:0),mvy=(k.s||k.arrowdown?1:0)-(k.w||k.arrowup?1:0),hasMove=mvx||mvy,pdx=n.player.x-v.x,pdy=n.player.y-v.y,base=Math.atan2(pdy,pdx),d=Math.hypot(pdx,pdy),moveAng=hasMove?Math.atan2(mvy,mvx):base+Math.PI,slot=v.packSlot||0,laneAng=moveAng+v.flankDir*(1.05*v.laneBias),backAng=moveAng+Math.PI+slot*.22,sideAng=base+v.flankDir*(1.2+Math.min(.6,d/260));if(v.moveType==="chaser")return{x:n.player.x+Math.cos(sideAng)*(v.trapRange+28+Math.abs(slot)*12),y:n.player.y+Math.sin(sideAng)*(v.trapRange+28+Math.abs(slot)*12)};if(v.moveType==="orbit"){const ring=base+v.orbitDir*(1.45+.45*Math.sin(n.time*1.7+v.phase))+slot*.14;return{x:n.player.x+Math.cos(ring)*(v.trapRange+54),y:n.player.y+Math.sin(ring)*(v.trapRange+54)}}if(v.moveType==="zigzag")return{x:n.player.x+Math.cos(laneAng)*(v.trapRange+72+Math.abs(slot)*16),y:n.player.y+Math.sin(laneAng)*(v.trapRange+72+Math.abs(slot)*16)};if(v.moveType==="scout")return{x:n.player.x+Math.cos(laneAng+slot*.18)*(v.trapRange+108),y:n.player.y+Math.sin(laneAng+slot*.18)*(v.trapRange+108)};return{x:n.player.x+Math.cos(backAng)*(v.trapRange+84+Math.abs(slot)*14),y:n.player.y+Math.sin(backAng)*(v.trapRange+84+Math.abs(slot)*14)}}
function stepEnemy(v,n,k,dt){if(v.dotTime>0&&v.dotDps>0){v.hp-=v.dotDps*dt;v.dotTime=Math.max(0,v.dotTime-dt)}const g=enemyGoal(v,n,k),goal=Math.atan2(g.y-v.y,g.x-v.x),gd=dist(g,v);let a=goal,s=v.speed;if(v.moveType==="chaser"){v.burstCd-=dt;if(v.burstTime>0){v.burstTime-=dt;s*=2.1;a=goal+v.flankDir*.15}else if(v.burstCd<=0&&gd>70&&gd<220){v.burstCd=rand(2,3.4);v.burstTime=.28}s*=gd<56?1.18:1.02}else if(v.moveType==="orbit"){v.feintCd-=dt;if(v.feintTime>0){v.feintTime-=dt;a=goal-v.orbitDir*1.3;s*=1.65}else{a=goal+v.orbitDir*(gd<40?1.7:.82);s*=gd<52?.62:1.16;if(v.feintCd<=0&&gd<170){v.feintCd=rand(1.6,2.6);v.feintTime=.22}}}else if(v.moveType==="zigzag"){a=goal+Math.sin(n.time*4.6*v.drift+v.phase)*1.05*v.weaveFlip;s*=1.28;if(Math.sin(n.time*1.7+v.phase)>.985)v.weaveFlip*=-1}else if(v.moveType==="scout"){v.dashCd-=dt;if(v.dashTime>0){v.dashTime-=dt;a=v.dashAngle;s*=3.8}else if(v.dashCd<=0){v.dashCd=rand(.7,1.15);v.dashTime=.24;v.dashAngle=goal+v.flankDir*1.15}}else if(v.moveType==="tank"){v.slamCd-=dt;if(v.chargeTime>0){v.chargeTime-=dt;a=v.chargeAngle;s*=4.4}else if(v.windup>0){v.windup-=dt;s*=.1;if(v.windup<=0){v.chargeTime=.48;v.chargeAngle=goal}}else if(v.slamTime>0){v.slamTime-=dt;a=goal+v.flankDir*1.35;s*=.55}else if(gd<190){v.windup=rand(.34,.56);v.slamCd=rand(2.5,4);v.slamTime=.26;s*=.22}else s*=.9}v.x+=Math.cos(a)*s*dt;v.y+=Math.sin(a)*s*dt;}

function drawCircle(ctx,x,y,r,fill,stroke,line=1){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.lineWidth=line;ctx.strokeStyle=stroke;ctx.stroke()}}
function drawProjectile(x,p){if(p.style==="needle"){x.strokeStyle=p.color;x.lineWidth=2;x.beginPath();x.moveTo(p.px,p.py);x.lineTo(p.x,p.y);x.stroke();drawCircle(x,p.x,p.y,p.size,p.color)}else if(p.style==="boomerang"){x.save();x.translate(p.x,p.y);x.rotate(p.spin||0);x.strokeStyle=p.color;x.lineWidth=3;x.beginPath();x.arc(0,0,p.size,Math.PI*.15,Math.PI*1.15);x.stroke();x.beginPath();x.arc(0,0,p.size*.65,Math.PI*.18,Math.PI*1.08);x.strokeStyle="rgba(255,255,255,.55)";x.lineWidth=1.5;x.stroke();x.restore()}else if(p.style==="bloom"){drawCircle(x,p.x,p.y,p.size+3,"rgba(251,191,36,.18)");drawCircle(x,p.x,p.y,p.size,p.color)}else drawCircle(x,p.x,p.y,p.size,p.color)}
function drawEnemy(x,e,time){drawCircle(x,e.x,e.y,e.r,e.color);if(e.dotTime>0&&e.dotDps>0)drawCircle(x,e.x,e.y,e.r+6,null,"rgba(134,239,172,.7)",2);if(e.moveType==="scout"){x.strokeStyle="rgba(255,255,255,.65)";x.lineWidth=1.5;x.beginPath();x.moveTo(e.x-6,e.y);x.lineTo(e.x+6,e.y);x.stroke();if(e.dashTime>0)drawCircle(x,e.x,e.y,e.r+7,null,"rgba(255,255,255,.35)")}else if(e.moveType==="chaser"&&e.burstTime>0)drawCircle(x,e.x,e.y,e.r+6,null,"rgba(255,255,255,.28)",1.5);else if(e.moveType==="tank"){if(e.windup>0)drawCircle(x,e.x,e.y,e.r+6,null,"rgba(248,113,113,.75)",2);if(e.chargeTime>0)drawCircle(x,e.x,e.y,e.r+10,null,"rgba(255,160,122,.55)",2);x.fillStyle="rgba(0,0,0,.18)";x.fillRect(e.x-5,e.y-2,10,4)}else if(e.moveType==="orbit"){drawCircle(x,e.x,e.y,e.r+4,null,"rgba(196,181,253,.35)");if(e.feintTime>0)drawCircle(x,e.x,e.y,e.r+8,null,"rgba(255,255,255,.45)",1.5)}else if(e.moveType==="zigzag"){x.strokeStyle="rgba(255,255,255,.45)";x.lineWidth=1;x.beginPath();x.moveTo(e.x-5,e.y+4);x.lineTo(e.x,e.y-4);x.lineTo(e.x+5,e.y+4);x.stroke();if(Math.abs(Math.sin(time*4.6*e.drift+e.phase))>.82)drawCircle(x,e.x,e.y,e.r+5,null,"rgba(255,255,255,.24)")}const hw=24,pct=clamp(e.hp/e.maxHp,0,1);x.fillStyle="rgba(0,0,0,.4)";x.fillRect(e.x-hw/2,e.y-e.r-12,hw,4);x.fillStyle="rgba(255,255,255,.8)";x.fillRect(e.x-hw/2,e.y-e.r-12,hw*pct,4)}

const Chip=({children})=><div className="rounded-xl bg-black/35 backdrop-blur px-2 py-1 text-[10px] md:text-[11px] text-slate-200">{children}</div>;
const Stat=({label,v,c})=><span className={c}>{label} <span className="text-white">{v}</span></span>;
const WeaponCard=({w,onPick})=><button onClick={()=>onPick(w.k)} className="text-left rounded-3xl border border-white/10 bg-white/5 hover:bg-white/10 transition p-4"><div className="flex items-start justify-between gap-3"><div className="text-lg font-semibold">{w.title}</div><div className="flex flex-wrap gap-1.5 text-[10px] font-medium"><Stat label="Damage" v={w.stats.find(s=>s.label==="Damage")?.value||"-"} c="text-rose-300"/><Stat label="Range" v={w.stats.find(s=>s.label==="Range")?.value||"-"} c="text-sky-300"/><Stat label="Speed" v={w.stats.find(s=>s.label==="Speed")?.value||"-"} c="text-amber-300"/></div></div><div className="text-[10px] uppercase tracking-[.14em] text-fuchsia-300 mt-1">{w.role}</div><div className="text-sm text-slate-300 mt-3 leading-5">{w.effect}</div></button>;
const UpgradeCard=({u,onPick})=><button onClick={()=>onPick(u)} className="text-left rounded-3xl border border-white/10 bg-white/5 hover:bg-white/10 transition p-4"><div className="text-lg font-semibold">{u.title}</div><div className="text-[10px] uppercase tracking-[.14em] text-fuchsia-300 mt-1">{u.family||"General"}</div><div className="text-sm text-slate-300 mt-3 leading-5">{u.body}</div></button>;
const Modal=({children})=><div className="absolute inset-0 bg-slate-950/86 backdrop-blur-sm flex items-center justify-center p-6"><div className="w-full max-w-5xl rounded-3xl border border-white/10 bg-slate-900/95 p-6 shadow-2xl">{children}</div></div>;
const SynthCard=({u,kept,burned,juice,onKeep,onBurn})=>{const m=juiceMeta(u),done=kept||burned;return <div className={`rounded-3xl border p-4 bg-white/5 ${kept?"border-emerald-400/50":burned?"border-amber-400/40":"border-white/10"}`}><div className="flex items-start justify-between gap-3"><div><div className="text-lg font-semibold">{u.title}</div><div className="text-[10px] uppercase tracking-[.14em] text-fuchsia-300 mt-1">{u.family}</div></div><div className="text-right text-xs text-slate-300"><div>Keep: <span className="text-emerald-300 font-semibold">{m.cost}</span></div><div>Render: <span className="text-amber-300 font-semibold">+{m.gain}</span></div></div></div><p className="text-sm text-slate-300 mt-3 leading-5">{u.body}</p><div className="mt-4 grid grid-cols-2 gap-2"><button disabled={done||juice<m.cost} onClick={()=>onKeep(u)} className="rounded-xl bg-emerald-400/15 hover:bg-emerald-400/25 disabled:opacity-35 disabled:hover:bg-emerald-400/15 px-3 py-2 text-sm">Stabilize</button><button disabled={done} onClick={()=>onBurn(u)} className="rounded-xl bg-amber-400/15 hover:bg-amber-400/25 disabled:opacity-35 px-3 py-2 text-sm">Render Juice</button></div>{kept&&<div className="mt-3 text-xs text-emerald-300">Permanent for the rest of the run.</div>}{burned&&<div className="mt-3 text-xs text-amber-300">Sacrificed into Juice.</div>}</div>};
const mkSpawn=enemy=>({id:gid(),x:enemy.x,y:enemy.y,r:enemy.r+10,life:.55,maxLife:.55,enemy});

export default function CryptBloomSurvivorOptimized(){const canvasRef=useRef(null),keysRef=useRef({}),shotRef=useRef(0),trailRef=useRef(0),rafRef=useRef(null),checked=useRef(false),[game,setGame]=useState(init),derived=useMemo(()=>({pressure:Math.min(100,Math.floor(game.time*1.2+game.enemies.length*1.4)),wavePct:clamp(game.waveTime/waveLen(game.wave),0,1)}),[game.time,game.enemies.length,game.waveTime,game.wave]);
useEffect(()=>{if(!checked.current){selfCheck();checked.current=true}},[]);
useEffect(()=>{if(game.phase!=="waveEnd")return;const id=setTimeout(()=>setGame(g=>g.phase==="waveEnd"?{...g,phase:"synthesis",messages:["Choose what survives the synthesis."],synthKeep:[],synthBurn:[]}:g),900);return()=>clearTimeout(id)},[game.phase]);
useEffect(()=>{const down=e=>{keysRef.current[e.key.toLowerCase()]=true;if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault()},up=e=>{keysRef.current[e.key.toLowerCase()]=false};window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up)}},[]);
useEffect(()=>{let last=performance.now();const loop=()=>{const now=performance.now(),dt=Math.min(.033,(now-last)/1e3);last=now;setGame(prev=>{if(prev.phase!=="playing")return prev;const n={...prev,time:prev.time+dt,waveTime:Math.max(0,prev.waveTime-dt),player:{...prev.player,hitFlash:Math.max(0,prev.player.hitFlash-dt*4),hp:clamp(prev.player.hp,0,prev.player.maxHp),shield:Math.max(0,prev.player.shield-dt*.25),pickupHasteTime:Math.max(0,prev.player.pickupHasteTime-dt)},systems:{...prev.systems,funeralHeatTime:Math.max(0,prev.systems.funeralHeatTime-dt)},invuln:Math.max(0,prev.invuln-dt),enemies:prev.enemies.map(v=>({...v})),projectiles:prev.projectiles.map(v=>({...v})),drops:prev.drops.map(v=>({...v})),trail:prev.trail.map(v=>({...v})),ash:prev.ash.map(v=>({...v})),expl:prev.expl.map(v=>({...v})),floaters:prev.floaters.map(v=>({...v})),spawns:prev.spawns.map(v=>({...v})),messages:prev.messages.slice(-2)};
if(n.waveTime<=0)return{...n,phase:"waveEnd",messages:["Wave End"],enemies:[],spawns:[],projectiles:[],drops:[],trail:[],ash:[],expl:[],floaters:[{id:gid(),x:W/2-44,y:H/2,text:"WAVE END",color:"#f8fafc",life:.85,vy:0}]};
const k=keysRef.current,mx=(k.d||k.arrowright?1:0)-(k.a||k.arrowleft?1:0),my=(k.s||k.arrowdown?1:0)-(k.w||k.arrowup?1:0),raw=Math.hypot(mx,my),len=raw||1;n.player.isMoving=raw>0;if(n.player.momentumEnabled)n.player.momentumMeter=clamp(n.player.momentumMeter+(n.player.isMoving?dt*.6:-dt*.9),0,1);const spd=1+n.player.pickupHasteTime*n.player.pickupHasteStrength*.4;n.player.x=clamp(n.player.x+mx/len*n.player.moveSpeed*spd*dt,PR,W-PR);n.player.y=clamp(n.player.y+my/len*n.player.moveSpeed*spd*dt,PR,H-PR);
trailRef.current-=dt;if(n.player.trailEnabled&&n.player.isMoving&&trailRef.current<=0){n.trail.push({id:gid(),x:n.player.x,y:n.player.y,radius:14,life:.45});trailRef.current=.12}n.trail.forEach(v=>v.life-=dt);n.trail=n.trail.filter(v=>v.life>0);n.ash.forEach(v=>v.life-=dt);n.ash=n.ash.filter(v=>v.life>0);n.expl.forEach(v=>v.life-=dt);n.expl=n.expl.filter(v=>v.life>0);n.floaters.forEach(v=>{v.life-=dt;v.y-=v.vy*dt});n.floaters=n.floaters.filter(v=>v.life>0);n.spawns.forEach(v=>v.life-=dt);const ready=n.spawns.filter(v=>v.life<=0);if(ready.length)n.enemies.push(...ready.map(v=>v.enemy));n.spawns=n.spawns.filter(v=>v.life>0);
n.spawnBudget+=(.22+n.time*.014+n.wave*.04)*dt;n.spawnCooldown-=dt;while(n.spawnBudget>=1&&n.spawnCooldown<=0){n.spawns.push(...spawnGroup(n.time+n.wave*12).map(mkSpawn));n.spawnBudget-=1;n.spawnCooldown=Math.max(1.25,3.1-n.time*.003)}
shotRef.current-=dt;const cd=n.player.cooldown/((1+n.player.momentumMeter*n.player.momentumAttackRate)*(1+n.systems.funeralHeatTime*n.systems.funeralHeatAttackRate)*(1+n.player.pickupHasteTime*n.player.pickupHasteStrength*.18));if(shotRef.current<=0){const cost=n.player.overdraw?n.player.overdrawHpCost:0,canFire=!n.player.overdraw||n.player.hp>Math.max(1.1,cost+.15);if(canFire){const s=fireShots(n.player,n.enemies);if(s.length){n.projectiles.push(...s);if(n.player.overdraw)n.player.hp=Math.max(1,n.player.hp-cost);shotRef.current=cd}else shotRef.current=.08}else shotRef.current=.08}
n.projectiles.forEach(v=>{v.px=v.x;v.py=v.y;if(v.style==="boomerang")stepBoom(v,n,dt);else{v.x+=v.vx*dt;v.y+=v.vy*dt;v.life-=dt}});n.projectiles=n.projectiles.filter(v=>v.life>0&&v.x>-40&&v.x<W+40&&v.y>-40&&v.y<H+40);n.enemies.forEach(v=>stepEnemy(v,n,k,dt));
if(n.player.trailEnabled)n.trail.forEach(z=>n.enemies.forEach(e=>{if(dist(z,e)<=z.radius+e.r)e.hp-=n.player.trailDamagePerSecond*dt}));if(n.systems.ashWakeEnabled)n.ash.forEach(z=>n.enemies.forEach(e=>{if(dist(z,e)<=z.radius+e.r)e.hp-=n.systems.ashWakeDps*dt}));
n.projectiles.forEach(p=>{for(const e of n.enemies){if(!p.hitIds.includes(e.id)&&dist(p,e)<=e.r+4){if(p.style==="boomerang"&&p.dotDps>0){e.dotDps=Math.max(e.dotDps||0,p.dotDps);e.dotTime=Math.max(e.dotTime||0,p.dotTime);n.floaters.push({id:gid(),x:e.x+rand(-6,6),y:e.y-6,text:`${Math.round(p.dotDps*10)/10}/s`,color:p.color,life:.55,vy:18})}else{e.hp-=p.damage;n.floaters.push({id:gid(),x:e.x+rand(-6,6),y:e.y-6,text:`-${Math.round(p.damage*10)/10}`,color:p.color,life:.55,vy:18})}p.hitIds.push(e.id);if(n.player.leechOnHit>0)n.player.hp+=Math.min(n.player.leechOnHit,n.player.maxHp-n.player.hp);if(p.pierceLeft>0)p.pierceLeft-=1;else p.life=0;break}}});
const survivors=[],expl=[];for(const e of n.enemies){if(e.hp<=0){n.kills+=1;n.drops.push({id:gid(),x:e.x,y:e.y,value:e.elite?3:1,type:"xp"});if(Math.random()<dropChance(n.systems,e))n.drops.push({id:gid(),x:e.x+rand(-8,8),y:e.y+rand(-8,8),value:n.systems.bloodNuggetHeal,type:"heal"});if(n.systems.corpseExplosionRadius>0)expl.push({x:e.x,y:e.y})}else survivors.push(e)}n.enemies=survivors;let chain=0;if(expl.length){expl.forEach(v=>{n.expl.push({id:gid(),x:v.x,y:v.y,r:n.systems.corpseExplosionRadius,life:.22});n.enemies.forEach(e=>{if(dist(v,e)<=n.systems.corpseExplosionRadius+e.r)e.hp-=n.systems.corpseExplosionDamage});if(n.systems.ashWakeEnabled)n.ash.push(ash(v.x,v.y,n.systems))});const post=[];for(const e of n.enemies){if(e.hp<=0){chain+=1;n.kills+=1;n.drops.push({id:gid(),x:e.x,y:e.y,value:1+n.systems.chainXpBonus,type:"xp"});if(Math.random()<dropChance(n.systems,e))n.drops.push({id:gid(),x:e.x+rand(-8,8),y:e.y+rand(-8,8),value:n.systems.bloodNuggetHeal,type:"heal"})}else post.push(e)}n.enemies=post}if(chain>0&&n.systems.funeralHeatEnabled)n.systems.funeralHeatTime=clamp(n.systems.funeralHeatTime+.8,0,1.4);
const magnet=mag(n.player);n.drops.forEach(d=>{const dd=dist(d,n.player);if(dd<magnet){const a=Math.atan2(n.player.y-d.y,n.player.x-d.x),sp=240+(magnet-dd)*4;d.x+=Math.cos(a)*sp*dt;d.y+=Math.sin(a)*sp*dt}});n.drops=n.drops.filter(d=>{if(dist(d,n.player)>=PR+DR+2)return true;if(d.type==="xp"){n.xp+=d.value;n.floaters.push({id:gid(),x:n.player.x+rand(-10,10),y:n.player.y-18,text:`+${d.value} XP`,color:"#34d399",life:.6,vy:20});if(n.player.harvestLineEnabled)n.player.pickupHasteTime=clamp(n.player.pickupHasteTime+.45,0,2.5)}else{const miss=n.player.maxHp-n.player.hp,heal=Math.min(d.value,Math.max(0,miss));n.player.hp+=heal;n.floaters.push({id:gid(),x:n.player.x+rand(-10,10),y:n.player.y-18,text:`+${heal} HP`,color:"#fb7185",life:.6,vy:20});const left=d.value-heal;if(left>0&&n.player.overhealShield)n.player.shield+=left}return false});
while(n.xp>=n.xpTarget){n.xp-=n.xpTarget;n.level+=1;n.pendingLevelUps+=1;n.xpTarget=xpT(n.level)}if(n.pendingLevelUps>0)return enter(n);for(const e of n.enemies){if(dist(e,n.player)<e.r+PR&&n.invuln<=0){let dmg=e.damage;if(n.player.shield>0){const a=Math.min(n.player.shield,dmg);n.player.shield-=a;dmg-=a}n.player.hp-=dmg;n.player.hitFlash=1;n.invuln=.5;n.messages=["Pressure is a positioning test."];if(n.player.hp<=0)return{...n,phase:"dead",messages:["The bloom overwhelmed you."]}}}return n});rafRef.current=requestAnimationFrame(loop)};rafRef.current=requestAnimationFrame(loop);return()=>{if(rafRef.current)cancelAnimationFrame(rafRef.current)}},[]);
useEffect(()=>{const c=canvasRef.current;if(!c)return;const x=c.getContext("2d");if(!x)return;x.clearRect(0,0,W,H);const bg=x.createLinearGradient(0,0,0,H);bg.addColorStop(0,"#0b1020");bg.addColorStop(1,"#111827");x.fillStyle=bg;x.fillRect(0,0,W,H);for(let i=0;i<80;i++){const xx=i*137.7%W,yy=i*97.3%H;x.fillStyle=i%3===0?"rgba(255,255,255,.05)":"rgba(167,139,250,.05)";x.fillRect(xx,yy,2,2)}x.strokeStyle="rgba(255,255,255,.06)";x.lineWidth=1;for(let xx=40;xx<W;xx+=40){x.beginPath();x.moveTo(xx,0);x.lineTo(xx,H);x.stroke()}for(let yy=40;yy<H;yy+=40){x.beginPath();x.moveTo(0,yy);x.lineTo(W,yy);x.stroke()}game.ash.forEach(z=>drawCircle(x,z.x,z.y,z.radius,`rgba(251,146,60,${.13*(z.life/Math.max(.1,game.systems.ashWakeDuration||1))})`));game.expl.forEach(e=>{drawCircle(x,e.x,e.y,e.r*(1-(e.life/.22)*.35),`rgba(251,191,36,${.22*(e.life/.22)})`);drawCircle(x,e.x,e.y,e.r*.55,`rgba(255,245,180,${.15*(e.life/.22)})`)});game.floaters.forEach(f=>{x.fillStyle=f.color;x.font=f.text==="WAVE END"?"bold 28px sans-serif":"12px sans-serif";x.globalAlpha=Math.max(0,Math.min(1,f.life/.6));x.fillText(f.text,f.x,f.y);x.globalAlpha=1});game.trail.forEach(z=>drawCircle(x,z.x,z.y,z.radius,`rgba(96,165,250,${.16*z.life})`));game.spawns.forEach(s=>{const a=s.life/s.maxLife;drawCircle(x,s.x,s.y,s.r*(1.15-a*.25),null,`rgba(248,113,113,${.8-a*.35})`,2);drawCircle(x,s.x,s.y,6+8*(1-a),`rgba(248,113,113,${.18+a*.08})`)});game.drops.forEach(d=>drawCircle(x,d.x,d.y,DR,d.type==="heal"?"#fb7185":d.value>1?"#f59e0b":"#34d399"));game.projectiles.forEach(p=>drawProjectile(x,p));game.enemies.forEach(e=>drawEnemy(x,e,game.time));if(game.player.shield>0)drawCircle(x,game.player.x,game.player.y,PR+7,null,"rgba(34,211,238,.65)",2);if(game.player.momentumEnabled&&game.player.momentumMeter>=.98){drawCircle(x,game.player.x,game.player.y,PR+11,null,"rgba(250,204,21,.9)",2);for(let i=0;i<4;i++){const a=i*Math.PI/2+game.time*8;drawCircle(x,game.player.x+Math.cos(a)*(PR+11),game.player.y+Math.sin(a)*(PR+11),2.5,"rgba(250,204,21,.95)")}}drawCircle(x,game.player.x,game.player.y,PR,game.player.hitFlash>0?"#fb7185":"#60a5fa","rgba(255,255,255,.7)",3)},[game]);
const chooseWeapon=k=>setGame(prev=>{if(prev.phase!=="start")return prev;const out=wBy(k).apply(prev.player,prev.systems);shotRef.current=0;return{...prev,phase:"playing",player:out.player,systems:out.systems,waveTime:waveLen(prev.wave),messages:[out.message]}});
const chooseUpgrade=u=>setGame(prev=>{if(prev.phase!=="levelup")return prev;const applied=u.apply(prev),wavePicks=prev.wavePicks.includes(u.key)?prev.wavePicks:[...prev.wavePicks,u.key],upgraded={...applied,wavePicks,messages:[...prev.messages.slice(-1),`${u.title} acquired for this wave.`]},resumed={...upgraded,phase:"playing",offered:[],player:{...upgraded.player,hp:clamp(upgraded.player.hp,0,upgraded.player.maxHp)}};return resumed.pendingLevelUps>0?{...enter(resumed),messages:[`${u.title} acquired. Another power awaits.`]}:resumed});
const synthKeep=u=>setGame(prev=>{const {cost}=juiceMeta(u);if(prev.phase!=="synthesis"||prev.synthKeep.includes(u.key)||prev.synthBurn.includes(u.key)||prev.juice<cost)return prev;return{...prev,juice:prev.juice-cost,synthKeep:[...prev.synthKeep,u.key]}});
const synthBurn=u=>setGame(prev=>{const {gain}=juiceMeta(u);if(prev.phase!=="synthesis"||prev.synthKeep.includes(u.key)||prev.synthBurn.includes(u.key))return prev;return{...prev,juice:prev.juice+gain,synthBurn:[...prev.synthBurn,u.key]}});
const nextWave=()=>setGame(prev=>{if(prev.phase!=="synthesis")return prev;const keys=[...new Set([...prev.permKeys,...prev.synthKeep])],base=rebuildPermanent(prev,keys),wave=prev.wave+1;shotRef.current=0;trailRef.current=0;return{...base,phase:"playing",wave,waveTime:waveLen(wave),time:prev.time,level:prev.level,xp:prev.xp,xpTarget:prev.xpTarget,pendingLevelUps:0,kills:prev.kills,juice:prev.juice,permKeys:keys,wavePicks:[],synthKeep:[],synthBurn:[],offered:[],enemies:[],spawns:[],projectiles:[],drops:[],trail:[],ash:[],expl:[],floaters:[],spawnBudget:0,spawnCooldown:1.2,messages:[`Wave ${wave} begins.`]}});
const restart=()=>{shotRef.current=0;trailRef.current=0;setGame(init())};
const waveUpgrades=game.wavePicks.map(uBy).filter(Boolean);
return <div className="min-h-screen bg-slate-950 text-slate-100 p-4 md:p-6"><div className="mx-auto max-w-6xl"><div className="rounded-[28px] border border-white/10 bg-slate-900/70 shadow-2xl overflow-hidden"><div className="relative"><canvas ref={canvasRef} width={W} height={H} className="block w-full h-auto bg-slate-950"/>
{game.phase==="start"&&<Modal><div className="mb-5"><div className="text-fuchsia-300 text-sm uppercase tracking-[.3em]">Start Run</div><h2 className="text-3xl font-semibold mt-2">Choose a starting weapon</h2><p className="text-slate-300 mt-2">Each starter now fires and looks different in play.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{WEAPONS.map(w=><WeaponCard key={w.k} w={w} onPick={chooseWeapon}/>)}</div></Modal>}
{game.phase==="levelup"&&<Modal><div className="mb-5"><div className="text-fuchsia-300 text-sm uppercase tracking-[.3em]">Wave Upgrade</div><h2 className="text-3xl font-semibold mt-2">Choose an upgrade</h2><p className="text-slate-300 mt-2">This power lasts until synthesis. Stabilize it with Juice after the wave to keep it.</p></div><div className="grid gap-4 md:grid-cols-3">{game.offered.map(u=><UpgradeCard key={u.key} u={u} onPick={chooseUpgrade}/>)}</div></Modal>}
{game.phase==="waveEnd"&&<div className="absolute inset-0 bg-slate-950/45 backdrop-blur-[2px] flex items-center justify-center"><div className="text-center"><div className="text-fuchsia-300 text-sm uppercase tracking-[.4em]">Wave {game.wave}</div><div className="text-6xl font-black tracking-tight mt-3">Wave End</div><div className="text-slate-300 mt-3">Enemies evaporate into synthesis.</div></div></div>}
{game.phase==="synthesis"&&<Modal><div className="flex flex-col md:flex-row md:items-end md:justify-between gap-4 mb-6"><div><div className="text-fuchsia-300 text-sm uppercase tracking-[.3em]">Wave {game.wave} Complete</div><h2 className="text-4xl font-semibold mt-2">Synthesis</h2><p className="text-slate-300 mt-2 max-w-2xl">Choose which wave upgrades become permanent. Stabilize key powers with Juice, or render unused upgrades into Juice for later.</p></div><div className="rounded-2xl bg-white/10 border border-white/10 px-4 py-3 text-right"><div className="text-xs uppercase tracking-[.18em] text-slate-400">Juice</div><div className="text-3xl font-bold text-emerald-300">{game.juice}</div></div></div>{waveUpgrades.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{waveUpgrades.map(u=><SynthCard key={u.key} u={u} juice={game.juice} kept={game.synthKeep.includes(u.key)} burned={game.synthBurn.includes(u.key)} onKeep={synthKeep} onBurn={synthBurn}/>)}</div>:<div className="rounded-3xl border border-white/10 bg-white/5 p-6 text-slate-300">No upgrades were collected this wave. Continue to the next wave and gather XP to create synthesis choices.</div>}<div className="mt-6 flex flex-col md:flex-row gap-3 md:items-center md:justify-between"><div className="text-xs text-slate-400">Unresolved upgrades are discarded when the next wave begins.</div><button onClick={nextWave} className="rounded-2xl bg-fuchsia-400/20 hover:bg-fuchsia-400/30 border border-fuchsia-300/30 px-5 py-3 font-semibold">Next Wave</button></div></Modal>}
{(game.phase==="dead"||game.phase==="won")&&<div className="absolute inset-0 bg-slate-950/84 backdrop-blur-sm flex items-center justify-center p-6"><div className="rounded-3xl border border-white/10 bg-slate-900/95 p-8 text-center shadow-2xl max-w-md w-full"><div className="text-fuchsia-300 text-sm uppercase tracking-[.3em]">{game.phase==="won"?"Victory":"Run Over"}</div><h2 className="text-3xl font-semibold mt-3">{game.messages.at(-1)}</h2><div className="text-slate-300 mt-3">Wave {game.wave} • Level {game.level} • {game.kills} kills</div><button onClick={restart} className="mt-6 rounded-xl bg-white/10 hover:bg-white/20 transition px-4 py-2">Restart</button></div></div>}
<div className="pointer-events-none absolute inset-x-0 top-0 p-2 md:p-2.5"><div className="flex items-start justify-between gap-2"><div className="pointer-events-auto flex items-center gap-2 flex-wrap"><Chip>Wave <span className="text-white">{game.wave}</span></Chip><Chip><span className="opacity-90">Lv {game.level}</span><span className="mx-1 opacity-60">•</span><span className="opacity-90">{game.kills}</span></Chip>{game.player.weaponKey&&<Chip>{wBy(game.player.weaponKey).title}</Chip>}<Chip>Juice <span className="text-emerald-300">{game.juice}</span></Chip>{game.player.overdraw&&<Chip>Bloodcast</Chip>}{game.player.momentumEnabled&&<Chip>Momentum {Math.round(game.player.momentumMeter*100)}%</Chip>}{game.systems.corpseExplosionRadius>0&&<Chip>Bloom</Chip>}</div><Chip>{derived.pressure}%</Chip></div><div className="absolute left-1/2 top-2 -translate-x-1/2 rounded-2xl bg-black/45 backdrop-blur px-4 py-2 text-center border border-white/10"><div className="text-[9px] uppercase tracking-[.22em] text-fuchsia-300">Wave Ends</div><div className="text-2xl font-bold tabular-nums text-white leading-none mt-0.5">{fmt(game.waveTime)}</div></div><div className="mt-2 space-y-1 max-w-[240px]"><div className="h-1.5 rounded-full bg-black/40 overflow-hidden"><div className="h-full bg-rose-400" style={{width:`${game.player.hp/game.player.maxHp*100}%`}}/></div><div className="h-1.5 rounded-full bg-black/40 overflow-hidden"><div className="h-full bg-emerald-400" style={{width:`${game.xp/game.xpTarget*100}%`}}/></div>{game.player.shield>0&&<div className="h-1.5 rounded-full bg-black/40 overflow-hidden"><div className="h-full bg-cyan-400" style={{width:`${Math.min(100,game.player.shield*25)}%`}}/></div>}</div></div>
<div className="pointer-events-none absolute bottom-2 left-2 right-2 flex items-end justify-between gap-2"><div className="pointer-events-auto text-[10px] md:text-[11px] text-slate-300 bg-black/30 backdrop-blur px-2 py-1 rounded-lg max-w-[56%] truncate">{game.messages.at(-1)}</div><div className="pointer-events-auto flex items-center gap-2 rounded-xl bg-black/35 backdrop-blur px-2 py-1 text-[10px] md:text-[11px] text-slate-200"><span>{game.phase==="start"?"Pick a weapon":"Move: WASD"}</span><span className="opacity-50">•</span><span>Green = XP</span><span className="opacity-50">•</span><span>Red = Heal</span><span className="opacity-50">•</span><button onClick={restart} className="pointer-events-auto px-2 py-0.5 bg-white/10 rounded-md hover:bg-white/20 transition">Restart</button></div></div>
</div></div></div></div>}
